name: Kartikey Attri


roll.no: 8025320046

Lab Assignment 2 — Matrix Operations


In [7]:
# Question 1 — Create a 20000 × 10000 Data File
import numpy as np

# Generate 20000 x 10000 matrix using different random generators
rows, cols = 20000, 10000

# Mix of different random distributions
data = np.zeros((rows, cols))
data[:5000, :]   = np.random.randint(0, 100, (5000, cols))          # integers
data[5000:10000,:] = np.random.uniform(0, 1, (5000, cols))          # uniform floats
data[10000:15000,:] = np.random.normal(50, 10, (5000, cols))        # normal dist
data[15000:, :]  = np.random.exponential(1.5, (5000, cols))         # exponential dist

# Save to file
np.save("data_matrix.npy", data)
print(f"Data file saved. Shape: {data.shape}")
print(f"File size: ~{data.nbytes / 1e6:.1f} MB")

Data file saved. Shape: (20000, 10000)
File size: ~1600.0 MB


In [8]:
# Question 2 — Compare Subsequent Rows to First Row
import numpy as np

# Load data (or use a smaller sample for demo)
# data = np.load("data_matrix.npy")
data = np.random.randint(0, 100, (5, 6))  # small demo matrix
print("Matrix:\n", data)

first_row = data[0]
print("\nFirst Row:", first_row)

print("\nComparison of each subsequent row with First Row:")
for i in range(1, len(data)):
    comparison = data[i] == first_row
    matching   = np.sum(comparison)
    print(f"  Row {i}: {data[i]}  | Matches with Row 0: {matching}/{len(first_row)} elements")

Matrix:
 [[78 89 53 66 62  9]
 [88 63 65 32 22 41]
 [83  3 78 98 74 59]
 [ 0 32 47 57 74 15]
 [75 76 78 49 24 42]]

First Row: [78 89 53 66 62  9]

Comparison of each subsequent row with First Row:
  Row 1: [88 63 65 32 22 41]  | Matches with Row 0: 0/6 elements
  Row 2: [83  3 78 98 74 59]  | Matches with Row 0: 0/6 elements
  Row 3: [ 0 32 47 57 74 15]  | Matches with Row 0: 0/6 elements
  Row 4: [75 76 78 49 24 42]  | Matches with Row 0: 0/6 elements


In [9]:
# Question 3 — Group Similar Elements into a Matrix
import numpy as np
from collections import defaultdict

data = np.random.randint(1, 6, (4, 5))  # values 1–5
print("Original Matrix:\n", data)

# Group positions by element value
groups = defaultdict(list)
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        groups[data[i, j]].append((i, j))

print("\nGrouped Elements:")
for value in sorted(groups):
    print(f"  Value {value}: positions {groups[value]}")

# Build a grouped matrix (each row = one group, padded with -1)
max_len = max(len(v) for v in groups.values())
grouped_matrix = np.full((len(groups), max_len), -1)
for idx, (val, positions) in enumerate(sorted(groups.items())):
    for col, pos in enumerate(positions):
        grouped_matrix[idx, col] = val  # store the value; positions stored above

print("\nGrouped Value Matrix (rows = unique values, padded with -1):\n", grouped_matrix)

Original Matrix:
 [[1 5 4 2 2]
 [2 1 3 3 1]
 [5 2 1 3 3]
 [3 5 4 2 2]]

Grouped Elements:
  Value 1: positions [(0, 0), (1, 1), (1, 4), (2, 2)]
  Value 2: positions [(0, 3), (0, 4), (1, 0), (2, 1), (3, 3), (3, 4)]
  Value 3: positions [(1, 2), (1, 3), (2, 3), (2, 4), (3, 0)]
  Value 4: positions [(0, 2), (3, 2)]
  Value 5: positions [(0, 1), (2, 0), (3, 1)]

Grouped Value Matrix (rows = unique values, padded with -1):
 [[ 1  1  1  1 -1 -1]
 [ 2  2  2  2  2  2]
 [ 3  3  3  3  3 -1]
 [ 4  4 -1 -1 -1 -1]
 [ 5  5  5 -1 -1 -1]]


In [10]:
# Question 4 — Add and Subtract Matrices
import numpy as np

A = np.random.randint(1, 20, (4, 4))
B = np.random.randint(1, 20, (4, 4))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Addition
add_result = A + B
print("\nA + B:\n", add_result)

# Subtraction
sub_result = A - B
print("\nA - B:\n", sub_result)

Matrix A:
 [[ 3  3  4  7]
 [ 6  8 13  6]
 [ 5 10 16  1]
 [18 13  8  1]]

Matrix B:
 [[ 1  7  3 19]
 [17 11  1  3]
 [10  4  1  5]
 [15 12  8 10]]

A + B:
 [[ 4 10  7 26]
 [23 19 14  9]
 [15 14 17  6]
 [33 25 16 11]]

A - B:
 [[  2  -4   1 -12]
 [-11  -3  12   3]
 [ -5   6  15  -4]
 [  3   1   0  -9]]


In [11]:
# Question 5 — n × n Square Matrix Where Sub-matrix Corner Sums Are Even
import numpy as np

def create_even_corner_matrix(n):
    """
    Creates an n x n matrix where for every 2x2 sub-matrix,
    the sum of opposite corner elements is even.
    Sum of diagonals (top-left + bottom-right) and (top-right + bottom-left) are both even.
    This holds when all elements are of the same parity (all even or all odd).
    """
    # Using all even numbers guarantees all sub-matrix corner sums are even
    matrix = np.array([[2 * (i * n + j + 1) for j in range(n)] for i in range(n)])
    return matrix

def verify_even_corners(matrix):
    n = matrix.shape[0]
    for i in range(n - 1):
        for j in range(n - 1):
            sub = matrix[i:i+2, j:j+2]
            s1 = int(sub[0,0]) + int(sub[1,1])  # main diagonal sum
            s2 = int(sub[0,1]) + int(sub[1,0])  # anti-diagonal sum
            if s1 % 2 != 0 or s2 % 2 != 0:
                return False, (i, j)
    return True, None

n = 4
mat = create_even_corner_matrix(n)
print(f"{n}x{n} Matrix:\n", mat)

valid, pos = verify_even_corners(mat)
print(f"\nAll 2x2 sub-matrix corner sums are even: {valid}")

4x4 Matrix:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

All 2x2 sub-matrix corner sums are even: True


In [12]:
# Question 6 — Row-wise Element Addition in Tuple Matrix
# Tuple matrix: each element is a tuple of numbers; add element-wise across each row

tuple_matrix = [
    [(1, 2), (3, 4), (5, 6)],
    [(7, 8), (9, 1), (2, 3)],
    [(4, 5), (6, 7), (8, 9)],
]

print("Tuple Matrix:")
for row in tuple_matrix:
    print(" ", row)

print("\nRow-wise Element Addition (sum of all tuples in each row):")
for i, row in enumerate(tuple_matrix):
    # Add tuples element-wise across the row
    result = tuple(sum(tup[k] for tup in row) for k in range(len(row[0])))
    print(f"  Row {i}: {row} → Sum = {result}")

Tuple Matrix:
  [(1, 2), (3, 4), (5, 6)]
  [(7, 8), (9, 1), (2, 3)]
  [(4, 5), (6, 7), (8, 9)]

Row-wise Element Addition (sum of all tuples in each row):
  Row 0: [(1, 2), (3, 4), (5, 6)] → Sum = (9, 12)
  Row 1: [(7, 8), (9, 1), (2, 3)] → Sum = (18, 12)
  Row 2: [(4, 5), (6, 7), (8, 9)] → Sum = (18, 21)
